# Generated by Django 5.1.1 on 2024-09-07 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drinks", "0002_customers_sales"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sales",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="sales",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="drink",
            name="sales_history",
            field=models.ManyToManyField(related_name="drinks", to="drinks.sales"),
        ),
        migrations.AlterField(
            model_name="customers",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="drink",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
